language: java
after_success:
  - mvn clean test jacoco:report coveralls:report
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2a68c0889ded63864017
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
